repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      # Linter
      - id: ruff
        args: [ --fix ]
      # Formatter
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
    - id: mypy
      args: [--strict, --ignore-missing-imports, '.']
      language: system
      pass_filenames: false
